name = "Timot Tech"
license = "MIT"
licenselink = ""
description = "Just a tech blog"
homepage = ""
tags = [
    "archive",
    "blog",
    "bootstrap",
    "dark",
    "dark mode",
    "docs",
    "gallery",
    "landing",
    "multilingual",
    "personal",
    "responsive"
]
features = ["search", "flexible", "modular"]
[author]
name = "Timot Tech"
homepage = ""
